[smtp]
server = ecsmtp.pdx.intel.com
port = 25

[sender]
address = noreply-nio-l2-agent@intel.com
display_name = L2 Regression Agent

[recipients]
# Comma-separated list of email addresses
to = emmanuel.a.araya.gamboa@intel.com, mario.alpizar.castro@intel.com, mauricio.segura.zuniga@intel.com, kalthireddyx.gunasekhar@intel.com, sebastian.porras.villarreal@intel.com
cc = freddy.p.salazar.cordero@intel.com, bhanu.vattikuti@intel.com, sathyahx.sv@intel.com, gaby.gomez.cambronero@intel.com, marco.a.ramirez.mota@intel.com
