[smtp]
server = ecsmtp.pdx.intel.com
port = 25

[sender]
address = noreply-nio-l2-agent@intel.com
display_name = L2 Regression Agent

[recipients]
# Comma-separated list of email addresses
to = emmanuel.a.araya.gamboa@intel.com, mario.alpizar.castro@intel.com, mauricio.segura.zuniga@intel.com
cc = carlos.a.aguilar.acuna@intel.com, marco.a.ramirez.mota@intel.com, jason.fonseca.cortes@intel.com
